# -*- coding: utf-8 -*-
"""Bard-Gemini running.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDe0yXXjcrETVtqBJyKIQ6W5MHmogFSq
"""



"""This illutsrates the code to run the data on Bard (Gemini), it uses PALM2 Vertex AI API and model is text-bison."""

!pip3 install google-cloud-aiplatform>=1.38

"""**QADI**"""

import csv
import time
import os
import pandas as pd
from google.colab import auth as google_auth
import vertexai
from vertexai.language_models import TextGenerationModel


google_auth.authenticate_user()

# Initialize Vertex AI
vertexai.init(project="YOUR_PROJECT_NAME", location="us-central1")


model = TextGenerationModel.from_pretrained("text-bison")


parameters = {
    "candidate_count": 1,
    "max_output_tokens": 1024,
    "temperature": 0.2,
    "top_p": 0.8,
    "top_k": 40
}

file_path = 'YE.txt'
csv_file_path = 'YE.csv'  # Output CSV file
csv_header = ['Dialectal', 'Dialectal to Modern Standard Arabic', 'Modern Standard Arabic to Dialectal']

max_retries = 3  # Set the maximum number of retry attempts

with open(file_path, 'r', encoding='utf8') as file, \
     open(csv_file_path, 'w', newline='', encoding='utf8') as csv_file:

    lines = file.readlines()
    csv_writer = csv.DictWriter(csv_file, fieldnames=csv_header)
    csv_writer.writeheader()

    for line in lines:
        if "__label__" not in line:
            sentence = line

            retries = 0
            while retries < max_retries:
                try:
                    response = model.predict(f"Translate this to Modern Standard Arabic {sentence}", **parameters)

                    response2 = model.predict(f"Translate this to Yemeni Arabic {response.text}", **parameters)

                    data = {
                        'Dialectal': sentence,
                        'Dialectal to Modern Standard Arabic': response.text,
                        'Modern Standard Arabic to Dialectal': response2.text,
                    }

                    csv_writer.writerow(data)
                    break
                except Exception as e:
                    print(f"Error: {e}")
                    retries += 1
                    time.sleep(1)

print('CSV record written successfully')
from google.colab import files
files.download(csv_file_path)

"""**With few-shot**"""

import csv
import time
import os
import pandas as pd
from google.colab import auth as google_auth
import vertexai
from vertexai.language_models import TextGenerationModel


google_auth.authenticate_user()

vertexai.init(project="arabicdialects2", location="us-central1")
parameters = {
    "candidate_count": 1,
    "max_output_tokens": 1024,
    "temperature": 0.9,
    "top_p": 1
}

model = TextGenerationModel.from_pretrained("text-bison")


file_path = 'MSA (1).txt'
csv_file_path = 'MSA_Tunis.csv'  # Output CSV file
csv_header = ['Modern Standard Arabic', 'Modern Standard Arabic to Dialectal']

max_retries = 3 # Set the maximum number of retry attempts

with open(file_path, 'r', encoding='utf8') as file, \
     open(csv_file_path, 'w', newline='', encoding='utf8') as csv_file:

    lines = file.readlines()
    csv_writer = csv.DictWriter(csv_file, fieldnames=csv_header)
    csv_writer.writeheader()

    for line in lines:
        if "__label__" not in line:
            sentence = line
            retries = 0
            while retries < max_retries:
                try:
                    response = model.predict(f"Below are examples of MSA sentences and their translations into Tunisian Arabic: 1. MSA: مرحبا، كيف حالك؟ Translated sentence: مرحبا، شحالك؟ 2. MSA: كم الساعة الآن؟ Translated sentence: شحال فالعداد؟ 3. MSA: هل يمكنك مساعدتي من فضلك؟Translated sentence: تقدر تعاونني من فضلك؟Your task is to translate the following sentence from Modern standard arabic (MSA) to Tunisian Arabic {sentence}", **parameters)

                    data = {
                        'Modern Standard Arabic': sentence,
                        'Modern Standard Arabic to Dialectal': response.text
                    }

                    csv_writer.writerow(data)
                    break
                except Exception as e:
                    print(f"Error: {e}")
                    retries += 1
                    time.sleep(1)

print('CSV record written successfully')
from google.colab import files
files.download(csv_file_path)